server:
  port: 8081

spring:
  application:
    name: scm
  datasource:
    url: jdbc:mysql://localhost:3306/scm
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true